[webservers]
web1 ansible_host=51.250.18.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
web2 ansible_host=37.230.169.73 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_connection=ssh